env:
  node: true
  commonjs: true
  mocha: true
  es2021: true
extends: 'eslint:recommended'
ignorePatterns: 
  - node_modules
  - examples
  - assets
  - vendor
  - lib
  - dist
  - temp
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - args: after-used
      caughtErrors: none
  no-var: 
    - error
  prefer-const: 
    - error
