env:
  node: true
  commonjs: true
  mocha: true
  es2021: true
extends: 'eslint:recommended'
ignorePatterns: 
  - node_modules
  - examples
  - assets
  - vendor
  - lib
  - dist
  - temp
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-unused-vars:
    - error
    - args: after-used
      caughtErrors: none
  no-var: 
    - error
  prefer-const: 
    - error
